[package]
name = "netimp"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
fantoccini = "0.21.5"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"]}
urlencoding = "2.1.3"
rustube = "0.6.0"

